void dbus_message_iter_close_container() {}
void dbus_message_iter_open_container() {}
void dbus_message_iter_append_basic() {}
void dbus_message_iter_recurse() {}
void dbus_message_iter_get_arg_type() {}
void dbus_message_iter_get_basic() {}
void dbus_message_iter_init () {}
void dbus_bus_get() {}
void dbus_message_new() {}
void dbus_message_iter_next() {}
void dbus_message_iter_init_append () {}
void dbus_message_unref() {}
void dbus_message_get_signature() {}
void dbus_message_get_args () {}
void dbus_connection_close() {}
void dbus_connection_unref() {}
void dbus_connection_get_dispatch_status() {}
void dbus_connection_ref() {}
void dbus_connection_dispatch() {}
void dbus_watch_set_data() {}
void dbus_watch_handle() {}
void dbus_timeout_set_data() {}
void dbus_timeout_handle() {}
void dbus_watch_get_data() {}
void dbus_timeout_get_enabled() {}
void dbus_timeout_get_interval() {}
void dbus_timeout_get_data() {}
void dbus_watch_get_flags() {}
void dbus_watch_get_unix_fd() {}
void dbus_watch_get_enabled() {}
void dbus_message_new_method_call() {}
void dbus_message_append_args() {}
void dbus_error_init() {}
void dbus_connection_send_with_reply_and_block() {}
void dbus_error_is_set() {}
void dbus_error_free() {}
void dbus_message_get_path() {}
void dbus_message_new_method_return() {}
void dbus_connection_send() {}
void dbus_connection_get_data() {}
void dbus_connection_set_data() {}
void dbus_connection_set_watch_functions() {}
void dbus_connection_set_timeout_functions() {}
void dbus_connection_set_wakeup_main_function() {}
void dbus_server_allocate_data_slot() {}
void dbus_server_get_data() {}
void dbus_server_set_watch_functions() {}
void dbus_server_set_timeout_functions() {}
void dbus_message_new_signal() {}
void dbus_bus_remove_match() {}
void dbus_message_get_type() {}
void dbus_connection_allocate_data_slot() {}
void dbus_server_set_data() {}
void dbus_bus_add_match() {}
void dbus_message_get_interface() {}
void dbus_message_get_sender() {}
void dbus_message_get_member() {}
void dbus_pending_call_unref() {}
void dbus_pending_call_steal_reply() {}
void dbus_message_is_method_call() {}
void dbus_message_is_signal() {}
void dbus_connection_free_data_slot() {}
void dbus_connection_send_with_reply() {}
void dbus_pending_call_set_notify() {}
void dbus_connection_get_is_connected() {}
void dbus_connection_open_private() {}
void dbus_bus_register() {}
void dbus_bus_get_unique_name() {}
void dbus_message_get_destination() {}
void dbus_pending_call_ref() {}
void dbus_connection_read_write_dispatch() {}
void dbus_pending_call_cancel() {}
void dbus_set_error_const() {}
void dbus_set_error() {}
void dbus_connection_add_filter() {}
void dbus_bus_request_name() {}
void dbus_message_iter_get_signature() {}
void dbus_free() {}
void dbus_message_iter_get_fixed_array() {}
void dbus_message_get_error_name() {}
void dbus_message_ref() {}
void dbus_message_new_error() {}
void dbus_connection_flush() {}
void dbus_connection_register_fallback() {}
void dbus_connection_register_object_path() {}
void dbus_message_set_no_reply() {}
void dbus_message_set_destination() {}
void dbus_connection_set_unix_user_function() {}
void dbus_address_escape_value() {}
void dbus_server_listen() {}
void dbus_server_set_new_connection_function() {}
void dbus_connection_remove_filter() {}
void dbus_bus_release_name() {}
void dbus_connection_unregister_object_path() {}
void dbus_connection_open() {}
void dbus_bus_get_private() {}
void dbus_connection_set_exit_on_disconnect () {}
void dbus_shutdown() {}
void dbus_signature_validate() {}
void dbus_signature_iter_next() {}
void dbus_message_iter_abandon_container() {}
void dbus_pending_call_block() {}
void dbus_connection_list_registered() {}
void dbus_threads_init_default() {}
void dbus_connection_try_register_object_path() {}
void dbus_message_get_no_reply() {}
void dbus_connection_get_object_path_data() {}
void dbus_set_error_from_message() {}
void dbus_message_set_path() {}
void dbus_signature_iter_init() {}
void dbus_signature_iter_recurse() {}
void dbus_signature_iter_get_current_type() {}
void dbus_message_iter_append_fixed_array() {}
void dbus_message_set_interface() {}
void dbus_free_string_array() {}
